### PR TITLE
New streamlined name file

### PR DESCRIPTION
**Pull request by fellennert**
Names were scraped from www.nordicnames.de, other first names and the gender they are (mainly) referring to were manually added (i.e., profane googling). R script matched 10566 out of 10566 correctly (abbreviations not included). I do not know about the Python script – I'm too stupid to execute it – maybe some adaptations are needed here (row names?). 
Names are now in alphabetical order and only the ones that are actually present in the parliament were kept (new file has 322 names instead of 1,391). Composed names (such as Per-Johan) that occur are included as well.

Moreover, I made changes to the members_of_parliament.csv file, replaced some abbreviated names by the real ones (but not all, Google and my skills had their limitations), updated genders and arraned the entries according to name (alphabetical order first name) and parliamentary period.

### CODE REVIEW

**Comment by ninpnin** [comment]
Cool! Quick sanity check: the names.csv file seems to be shorter than before, is that a problem? Were there duplicates before?

**Comment by ninpnin** [comment]
Oh now I get what you wrote. LGTM.

**Comment by ninpnin** [comment]
Though we might want to keep the extra names for future additions?

**Comment by fellennert** [comment]
Yeah, we could do that as well. Should I then include the entirety of the names from Nordicnames.de (around 15,000 entries)? Shouldn’t make much of a difference now, but be pretty helpful in the future. 
However, I then would also suggest to change the matching code so that it can handle composed names better (i.e., just take the first name before the -).

**Comment by ninpnin** [comment]
That's a very reasonable suggestion. Do you have the time to implement it and push it here in one more commit? I'll take care of the python part after that.

**Comment by fellennert** [comment]
Yes, absolutely, will do it within the next hour. On another note: the gender categories in the name file and the meta data file are different („man/woman“ and „masculine/feminine“). Wouldn’t it make sense to equalize them (I would just do „m/f“ and, if applicable in the future, extend it to „m/f/d“)? Just a thought of mine, because I repeatedly stumbled across this problem while working with the data (at one point I had coded some as „male“ which messed things up even more).

**Review by ninpnin — COMMENTED** [review]
What are the row numbers for? EDIT: I suppose the pandas to_csv spits those out automatically, and you picked them up?  I guess what goes around, comes around. :sweat_smile:

**Comment by MansMeg** [comment]
Yes. We should normalize the categorizes male/female instead of different categories.

**Comment by fellennert** [comment]
> What are the row numbers for? EDIT: I suppose the pandas to_csv spits those out automatically, and you picked them up? I guess what goes around, comes around. 😅

Yes, exactly. sorry, I will fix that in a sec. 

> Yes. We should normalize the categorizes male/female instead of different categories.

Also, I will do the male/female normalization.

**Pull request merged**
